// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dndemo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240902203436_BlobColumns2")]
    partial class BlobColumns2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WBinAblageLimited", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("blob");

                    b.HasKey("Id");

                    b.ToTable("WBinAblageLimited");
                });

            modelBuilder.Entity("WBinAblageUnlimited", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("blob");

                    b.HasKey("Id");

                    b.ToTable("WBinAblageUnlimited");
                });
#pragma warning restore 612, 618
        }
    }
}
