// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dndemo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240902190837_BlobColumns")]
    partial class BlobColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WBinAblage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("blob");

                    b.HasKey("Id");

                    b.ToTable("WBinAblage");
                });

            modelBuilder.Entity("WBinAblageSplitted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("blob");

                    b.HasKey("Id");

                    b.ToTable("WBinAblageSplitted");
                });
#pragma warning restore 612, 618
        }
    }
}
